### ISSUE TITLE
Prepare data stage

### ISSUE THREAD

**Issue by YushannWang** [isyangshu/Surgformer#4]
Hi, thanks for the good work!
Prepare your data stage
Traceback (most recent call last):
  File "/root/private_data/surgical/datasets/data_preprosses/generate_labels_ch80.py", line 114, in <module>
    main()
  File "/root/private_data/surgical/datasets/data_preprosses/generate_labels_ch80.py", line 67, in main
    assert frame_id % fps == frame_id_
AssertionError

Can I comment out assert frame_i% fps==frame_i_?

**Comment by isyangshu** [comment]
This is just to help you make sure the ground truth and image are aligned.
Because the original video is 25FPS, and the ground truth labels provided are also 25FPS, “assert” can help avoid potential errors when you select labels for 1FPS video frames.

**Comment by YushannWang** [comment]
Thank you for your reply. Not commenting on this will result in processing failure. The results reproduced after commenting are very poor
{"train_lr": 4.510152111431054e-07, "train_min_lr": 1.07148874472873e-08, "train_loss": 1.5460823246728124, "train_loss_scale": 1.0, "train_weight_decay": 0.05000000000000185, "val_loss": 1.5391584940072967, "val_acc1": 38.41440098102724, "val_acc5": 91.82157561816739, "epoch": 49, "n_parameters": 177985543}
{"Final top-1": 39.623755522527844, "Final Top-5": 91.24844758433943}

**Comment by Dirck-YHP** [comment]
> Thank you for your reply. Not commenting on this will result in processing failure. The results reproduced after commenting are very poor {"train_lr": 4.510152111431054e-07, "train_min_lr": 1.07148874472873e-08, "train_loss": 1.5460823246728124, "train_loss_scale": 1.0, "train_weight_decay": 0.05000000000000185, "val_loss": 1.5391584940072967, C38.41440098102724, "val_acc5": 91.82157561816739, "epoch": 49, "n_parameters": 177985543} {"Final top-1": 39.623755522527844, "Final Top-5": 91.24844758433943}

hello,i got the same ploblem with u ,the running result is very poor such as "Epoch: [12]  [2160/5396]  eta: 0:26:26  lr: 0.000021  min_lr: 0.000002  loss: 1.4684 (1.6259)  loss_scale: 8192.0000 (8646.9005)  weight_decay: 0.0500 (0.0500)  grad_norm: 1.7589 (inf)  time: 0.5066  data: 0.0004  max mem: 9176", i dont know how to improve?
btw, i closed the deepspeed, is it the reason?

**Comment by isyangshu** [comment]
I guess you didn't process the video frames and their corresponding annotations correctly.

You need to check whether the number of training sets is more than 80k and less than 90k.

We extract directly at 1FPS in datasets/data_preprosses/extract_frames_ch80.py and manually align the label when generating pkl in datasets/data_preprosses/generate_labels_ch80.py (since the ground truth annotated in 30 FPS).

We will provide our own pkl files soon, and you can just directly extract the frames in 1FPS.

You can also try AutoLaparo Dataset, it's easier to generate the pkl files for training, whic can help rule out other issues.

**Comment by Dirck-YHP** [comment]
> I guess you didn't process the video frames and their corresponding annotations correctly.
> 
> You need to check whether the number of training sets is more than 80k and less than 90k.
> 
> We extract directly at 1FPS in datasets/data_preprosses/extract_frames_ch80.py and manually align the label when generating pkl in datasets/data_preprosses/generate_labels_ch80.py (since the ground truth annotated in 30 FPS).
> 
> We will provide our own pkl files soon, and you can just directly extract the frames in 1FPS.
> 
> You can also try AutoLaparo Dataset, it's easier to generate the pkl files for training, whic can help rule out other issues.

Thanks for your reply.I've tested the size of training set, it's 81k.I checked the code and i didn't find any problem.As you mentioned,i've only tried cholec80 so far, so i will try AutoLaparp Dataset soon.
And I truly hope that i can try your pkl file for training to figure out my problem

**Comment by YushannWang** [comment]
Thanks for your reply. I am looking forward to the revised version.

**Comment by YushannWang** [comment]
The command python datasets/data_preprosses/extract_frames_autolaparo.py also throws an error:
generate_labels_autolaparo.py", line 65, in main
    info['phase_name'] = id2phase[int(phase[1])]
KeyError: 7

Looking forward to uploading updated versions

**Comment by isyangshu** [comment]
I'm sorry for this mistake.
Since the labels in AutoLaparo are 1-7, but we need labels 0-6 for training.
We need to use phase[1]-1 to match 0-6.
phase = phase_results[frame_id].strip().split()
assert int(phase[0]) == frame_id + 1
phase_id = int(phase[1]) - 1
info['phase_gt'] = phase_id
info['phase_name'] = id2phase[phase_id]

**Comment by carlosh93** [comment]
Hi @isyangshu, I have the same issue for Cholec80. I processed the videos with `python datasets/data_preprosses/extract_frames_ch80.py`, but then, if I do `python datasets/data_preprosses/generate_labels_ch80.py,`, I got the AssertionError. Could you please provide any suggestions on how to solve this error? I'm only interested in Cholec80, not AutoLaparo. Many thanks in advance for your help.

**Comment by isyangshu** [comment]
I am re-downloading the original video and I expect to get back to you tomorrow or the day after tomorrow.

**Comment by isyangshu** [comment]
Sorry for the mistakes. In the initial version of extract_frames_ch80.py, I sampled directly at original fps, so I got all the video frames about Cholec80 (the number also corresponds to the official annotations one by one). On this basis, I used assert int(phase[0]) == frame_id in generate_labels_ch80.py to match the corresponding annotations. Later, I noticed that I could keep only the required frames and rename them to reduce the confusion between original frame id and frame id, so I rewrote extract_frames_ch80.py and generate_labels_ch80.py according to the AutoLaparo model without testing from the original data.

I notice some issues:
If AssertionError occurred at Line 67
Line 66:  info['frame_id'] = frame_id // fps (not %)
Line 67:  assert frame_id // fps == frame_id_ (not %)

If AssertionError occurred at Line 76, I will continue to fix bug after obtaining the original video data.

**Comment by isyangshu** [comment]
> Thank you for your reply. Not commenting on this will result in processing failure. The results reproduced after commenting are very poor {"train_lr": 4.510152111431054e-07, "train_min_lr": 1.07148874472873e-08, "train_loss": 1.5460823246728124, "train_loss_scale": 1.0, "train_weight_decay": 0.05000000000000185, "val_loss": 1.5391584940072967, "val_acc1": 38.41440098102724, "val_acc5": 91.82157561816739, "epoch": 49, "n_parameters": 177985543} {"Final top-1": 39.623755522527844, "Final Top-5": 91.24844758433943}

Sorry for the mistakes. I notice that current file will generate wrong pkl files for training. Since I store 'frame_id % fps' as frame id, thus for each video we only have fps=25 frames for training. Due to data license restrictions, I can only provide the pkl file here, you can get it here: https://hkustconnect-my.sharepoint.com/:f:/g/personal/syangcw_connect_ust_hk/Et8_FZe9ahdKkSWNe98ygWsBiBAKdE1iarDyn4oeaZ26Pg?e=ycZxtM

Sorry for the inconvenience and untimely reply again. The error came from my optimization of data preprocessing code without validation. AssertError also comes from here.
